{application,git_handler,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{git_handler_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[git_handler,git_handler_app,git_handler_sup,
                        lib_git_handler]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
